# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f332fb01261c01e51e865517b840b1ec903b81d98e73e165fa7fcc4706aa840c37ee970a2a0cf8e67d6de07bcc0e950f89133bcceaa2c2e240eb57e997b350ce
  paypal_host: https://www.sandbox.paypal.com
  app_host:    http://3f8156ab.ngrok.io
  gmail_username: scr.ownerr@gmail.com
  gmail_password: scr.ownerr123
  facilitator_account: omairr.azam-facilitator@gmail.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 294ae66ded03a88a7bf748628c67d1b955f9d5d0a6ac2d8422adf1cca4bbf89bc483b74ac901b3da7ff5d0603bfc746bc0636a63a24794e699a09fa276960fa3
  #paypal_host: https://www.paypal.com
  paypal_host: https://www.sandbox.paypal.com
  facilitator_account: omairr.azam-facilitator@gmail.com
  app_host: http://indextresearch.com
  gmail_username: scr.ownerr@gmail.com
  gmail_password: scr.ownerr123
